// BetterAuth server instance. Shared between apps/api (which mounts auth.handler)
// and apps/web (which calls auth.api.getSession() from Server Components / Route
// Handlers when SSR-side session reads are needed).
//
// Keep this file env-light: it reads BETTER_AUTH_SECRET / BETTER_AUTH_URL /
// WEB_ORIGIN at construction time. Both apps must provide them.

import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { db } from '@neuronexus/db/client';
import { sendEmail } from './email.ts';

function requireEnv(key: string): string {
  const v = process.env[key];
  if (!v) throw new Error(`Missing required env var: ${key}`);
  return v;
}

const trustedOrigins = [process.env.WEB_ORIGIN ?? 'http://localhost:3001'];
const WEB_ORIGIN = process.env.WEB_ORIGIN ?? 'http://localhost:3001';

export const auth = betterAuth({
  baseURL: requireEnv('BETTER_AUTH_URL'),
  secret: requireEnv('BETTER_AUTH_SECRET'),
  trustedOrigins,
  database: drizzleAdapter(db, { provider: 'pg' }),
  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    requireEmailVerification: false,
    minPasswordLength: 8,
    // Password-reset email. The token in `url` is generated by BetterAuth;
    // the landing page on the web side exchanges it for a new password.
    sendResetPassword: async ({ user, url }) => {
      const resetUrl = new URL('/auth/reset-password', WEB_ORIGIN);
      // Most of the time `url` already points at the frontend; fall back to
      // our own landing page if it's pointing back at the API.
      const target = url.startsWith(WEB_ORIGIN) ? url : resetUrl.toString();
      await sendEmail({
        to: user.email,
        subject: 'NeuroNexus — сброс пароля',
        tag: 'password-reset',
        text: [
          `Привет, ${user.name ?? 'друг'}!`,
          '',
          'Мы получили запрос на сброс пароля. Если это не вы — просто проигнорируйте письмо.',
          '',
          `Ссылка: ${target}${target.includes('?') ? '&' : '?'}token=${encodeURIComponent(
            new URL(url).searchParams.get('token') ?? '',
          )}`,
          '',
          'Ссылка работает 1 час.',
        ].join('\n'),
      });
    },
  },
  session: {
    expiresIn: 60 * 60 * 24 * 30, // 30 days
    updateAge: 60 * 60 * 24, // refresh token daily
  },
  advanced: {
    // Different origins for api (:3000) and web (:3001) in dev.
    defaultCookieAttributes: {
      sameSite: 'lax',
      secure: process.env.NODE_ENV === 'production',
    },
  },
});

export type Auth = typeof auth;
