// Realistic seed content for a fullstack .NET + React developer who's also
// learning English and computer-science fundamentals. Consumed by src/seed.ts.
//
// GOAL (reseed 2026-06): cards that look like REAL daily usage — full-bodied
// explanations with code blocks, mermaid diagrams, LaTeX formulas, comparison
// tables and markdown structure — not terse one-line stubs. The seed doubles as
// a live showcase of every rich-content feature the renderer supports.
//
// Each seed entry is a NOTE (note-types M1 model). A note references a builtin
// note-type by `kind`, carries `fields` (field-name → value), and may carry
// note-level `tags`. The seeder runs `generateCards` over the note-type + field
// values to produce one-or-more `cards` rows, then replays each note's
// `ratings` through ts-fsrs onto the generated card(s).
//
// ── Authoring contract (must match apps/web/src/lib/render-card.tsx) ──────────
// Field values are MARKDOWN SOURCE. markdown → HTML → sanitize happens at the
// render edge, never here. So:
//   * Code blocks:  ```ts ``` / ```sql ``` / ```bash ``` / ```json ``` / ```csharp ```.
//                   Highlighted langs: ts js python bash json sql xml css go rust
//                   markdown yaml. `csharp` is NOT in that set → it renders as a
//                   plain monospace block (no colours) — still a proper code block.
//   * Math (KaTeX): INLINE `\( … \)`, DISPLAY `\[ … \]`. In a TS string a single
//                   backslash must be DOUBLED: `'\\( O(\\log n) \\)'` produces the
//                   source `\( O(\log n) \)`. Put display math on its own line with
//                   blank lines around it so it renders as a centred block.
//   * Mermaid:      a ```mermaid ``` fence (rendered to an SVG island, theme dark,
//                   securityLevel strict). Quote node labels that contain special
//                   chars: `A["O(log n)"]`.
//   * Tables / headings / lists / blockquotes: standard markdown. ALWAYS leave a
//                   blank line before a fence / table / list / heading / quote so
//                   markdown-it parses it as its own block.
//   * `<T>` and other angle-bracket tokens go inside inline-code backticks
//     (`` `<T>` ``) so they (a) display literally and (b) survive the engine's
//     plaintext extraction (a bare `<T>` is stripped → empty front → card skipped).
//   * NEVER emit a literal `{{Front}}` / `{{Back}}` / `{{Text}}` / `{{Extra}}`
//     token inside a field value (the cloze `{{c1::…}}` markup is the only
//     double-brace form the engine expects). JSX single-brace `{x}` is fine.

import { type Rating, type RenderKind } from '@neuronexus/shared';

export type DeckColor = 'lime' | 'amber' | 'violet' | 'sky' | 'rose' | 'neutral';

export interface NoteSeed {
  /** Which builtin note-type backs this note. Defaults to 'basic'. */
  kind?: Extract<RenderKind, 'basic' | 'cloze' | 'typein'>;
  /** Field values keyed by field name. MARKDOWN SOURCE (rendered at the edge). */
  fields: Record<string, string>;
  tags?: string[];
  /** Replay these ratings to shape FSRS state. Omit → new card. */
  ratings?: Rating[];
}

export interface DeckSeed {
  name: string;
  color: DeckColor;
  children?: DeckSeed[];
  notes?: NoteSeed[];
}

/**
 * Join markdown lines with single newlines. Writing each line as a plain quoted
 * string keeps code-fence/mermaid backticks and `$` literal (no collision with a
 * TS template literal) and keeps math escaping readable (`'\\( … \\)'`). Use an
 * empty-string element `''` to emit the blank line markdown needs before a fence,
 * table, list, heading or blockquote.
 */
const md = (...lines: string[]): string => lines.join('\n');

interface NoteOpts {
  tags?: string[];
  ratings?: Rating[];
}

/** Basic front/back note (markdown source on both sides). */
function basic(front: string, back: string, opts: NoteOpts = {}): NoteSeed {
  return { kind: 'basic', fields: { Front: front, Back: back }, tags: opts.tags, ratings: opts.ratings };
}

/** Cloze note — `{{c1::answer}}` markup in `text`, optional `extra` reveal note. */
function cloze(text: string, extra: string, opts: NoteOpts = {}): NoteSeed {
  return { kind: 'cloze', fields: { Text: text, Extra: extra }, tags: opts.tags, ratings: opts.ratings };
}

/** Type-in note — the answer is typed and LCS-diffed against `back`. */
function typein(front: string, back: string, opts: NoteOpts = {}): NoteSeed {
  return { kind: 'typein', fields: { Front: front, Back: back }, tags: opts.tags, ratings: opts.ratings };
}

// Rating shorthand — deliberately varied so stats / heatmap / retention look
// natural across the catalog (not every card mature, not every card new).
const MATURE: Rating[] = [3, 3, 3, 4, 3, 3];
const STUDIED: Rating[] = [3, 3, 3];
const LEARNING: Rating[] = [3];
const ROUGH: Rating[] = [3, 2, 3, 2, 3];
const LAPSED: Rating[] = [3, 3, 3, 1, 3, 3];
const EASY: Rating[] = [4, 4, 3, 4];
const NEW: Rating[] = [];

export const SEED_DECKS: DeckSeed[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // .NET
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: '.NET',
    color: 'violet',
    children: [
      {
        name: 'C#',
        color: 'violet',
        notes: [
          basic(
            'Value types vs reference types — где живут и как копируются?',
            md(
              'Разделение по семантике копирования и месту хранения.',
              '',
              '| | Value type | Reference type |',
              '| --- | --- | --- |',
              '| Примеры | `struct`, `enum`, `int`, `bool` | `class`, `interface`, `delegate`, `string` |',
              '| Хранение | инлайн (стек / внутри объекта) | объект в куче, на стеке — ссылка |',
              '| Присваивание | копия **значения** | копия **ссылки** (тот же объект) |',
              '| Равенство по умолчанию | по значению полей | по ссылке |',
              '',
              '> `string` — reference type, но ведёт себя как value: immutable + перегружённый `==`.',
            ),
            { tags: ['csharp', 'fundamentals'], ratings: MATURE },
          ),
          basic(
            '`record` vs `class` — что меняет ключевое слово record?',
            md(
              '`record` — это `class` (или `struct`) с авто-сгенерированной семантикой значения:',
              '',
              '- **value equality** — `Equals`/`GetHashCode` по всем полям;',
              '- **`with`-выражения** — недеструктивное копирование;',
              '- **деконструкция** и читаемый `ToString()`.',
              '',
              '```csharp',
              'public record Money(decimal Amount, string Currency);',
              '',
              'var a = new Money(10m, "USD");',
              'var b = a with { Amount = 20m }; // новый объект, a не тронут',
              'Console.WriteLine(a == new Money(10m, "USD")); // True — по значению',
              '```',
            ),
            { tags: ['csharp'], ratings: STUDIED },
          ),
          basic(
            '`async`/`await` — что генерирует компилятор и создаёт ли поток?',
            md(
              'Компилятор переписывает метод в **state machine**. `await` НЕ создаёт поток —',
              'он регистрирует продолжение (continuation) как callback на `TaskAwaiter` и',
              'возвращает управление вызывающему. Когда `Task` завершится — продолжение',
              'выполнится (на захваченном `SynchronizationContext`, если он есть).',
              '',
              '```csharp',
              'async Task<int> LoadAsync(HttpClient http) {',
              '    var json = await http.GetStringAsync(url); // suspension point',
              '    return json.Length;                        // continuation',
              '}',
              '```',
              '',
              'Поток освобождается на время ожидания I/O — в этом весь смысл async:',
              '',
              '```mermaid',
              'sequenceDiagram',
              '    participant T as Thread pool',
              '    participant IO as I/O (сеть/диск)',
              '    T->>IO: запуск GetStringAsync',
              '    Note over T: await — поток ВОЗВРАЩЁН в пул',
              '    IO-->>T: данные готовы',
              '    Note over T: продолжение на свободном потоке',
              '```',
            ),
            { tags: ['csharp', 'async'], ratings: ROUGH },
          ),
          basic(
            '`Task` vs `ValueTask` — когда какой?',
            md(
              '| | `Task<T>` | `ValueTask<T>` |',
              '| --- | --- | --- |',
              '| Тип | class (heap alloc всегда) | struct (без alloc, если результат готов синхронно) |',
              '| `await` дважды | можно | **нельзя** (UB) |',
              '| `Task.WhenAll` / кэш | удобно | нужно `.AsTask()` |',
              '',
              'Бери `ValueTask` для **горячих** путей, которые **часто завершаются синхронно**',
              '(кэш-хит). По умолчанию — `Task`: проще и безопаснее.',
            ),
            { tags: ['csharp', 'async', 'perf'], ratings: LEARNING },
          ),
          basic(
            '`ConfigureAwait(false)` — зачем и где?',
            md(
              'Говорит «не возвращай продолжение на исходный `SynchronizationContext`».',
              '',
              '- **библиотеки** → почти всегда `false` (не зависим от контекста вызывающего, нет риска deadlock);',
              '- **классический UI** (WinForms/WPF) → `true`, чтобы вернуться в UI-поток;',
              '- **ASP.NET Core** → контекста нет, разницы по корректности нет.',
              '',
              '```csharp',
              'var data = await _repo.GetAsync(id).ConfigureAwait(false);',
              '```',
            ),
            { tags: ['csharp', 'async'], ratings: STUDIED },
          ),
          basic(
            '`IEnumerable<T>` vs `IQueryable<T>` — где выполняется фильтр?',
            md(
              '- `IEnumerable<T>` — **LINQ-to-Objects**, выполняется в памяти процесса.',
              '- `IQueryable<T>` — строит **expression tree**, провайдер (EF Core) переводит его в SQL.',
              '',
              'Ловушка: приведёшь `IQueryable` к `IEnumerable` (`AsEnumerable()`) слишком рано —',
              'и `Where` уедет в C# уже ПОСЛЕ выгрузки всей таблицы:',
              '',
              '```csharp',
              '// уходит в SQL: WHERE IsActive = 1',
              'db.Users.Where(u => u.IsActive).ToList();',
              '',
              '// тянет ВСЕХ из БД, фильтрует в памяти — антипаттерн',
              'db.Users.AsEnumerable().Where(u => u.IsActive).ToList();',
              '```',
            ),
            { tags: ['csharp', 'linq', 'ef'], ratings: MATURE },
          ),
          basic(
            'LINQ deferred execution — когда запрос реально выполнится?',
            md(
              '`Where` / `Select` / `OrderBy` строят **итератор**, но НЕ исполняют его.',
              'Триггер материализации:',
              '',
              '- `ToList()` / `ToArray()` / `ToDictionary()`',
              '- `First()` / `Single()` / `Count()` / `Any()`',
              '- `foreach`',
              '',
              '```csharp',
              'var q = nums.Where(n => n > 0); // ничего не считается',
              'nums.Add(5);',
              'var list = q.ToList();          // вот ТУТ, и 5 уже учтётся',
              '```',
            ),
            { tags: ['csharp', 'linq'], ratings: STUDIED },
          ),
          basic(
            'Pattern matching — switch expression',
            md(
              'Выражение (возвращает значение), exhaustive через discard `_`:',
              '',
              '```csharp',
              'string Sign(int x) => x switch {',
              '    > 0 => "positive",',
              '    < 0 => "negative",',
              '    _   => "zero",',
              '};',
              '',
              'decimal Discount(Customer c) => c switch {',
              '    { Tier: "gold", Years: > 5 } => 0.2m,',
              '    { Tier: "gold" }            => 0.1m,',
              '    _                           => 0m,',
              '};',
              '```',
            ),
            { tags: ['csharp'], ratings: STUDIED },
          ),
          basic(
            '`Span<T>` / `Memory<T>` — зачем?',
            md(
              'Zero-allocation окно над массивом / строкой / `stackalloc`:',
              '',
              '- `Span<T>` — `ref struct`, живёт **только на стеке** (нельзя в поле класса, в async, в лямбду);',
              '- `Memory<T>` — можно держать на куче и в async.',
              '',
              '```csharp',
              'ReadOnlySpan<char> s = "2026-06-08";',
              'int year = int.Parse(s.Slice(0, 4)); // без подстроки, без alloc',
              '```',
            ),
            { tags: ['csharp', 'perf'], ratings: LEARNING },
          ),
          basic(
            '`yield return` — что под капотом?',
            md(
              'Ленивый итератор. Компилятор генерирует класс-стейт-машину, реализующий',
              '`IEnumerator<T>`; тело метода **возобновляется** на каждом `MoveNext()`.',
              '',
              '```csharp',
              'IEnumerable<int> Fib() {',
              '    int a = 0, b = 1;',
              '    while (true) { yield return a; (a, b) = (b, a + b); }',
              '}',
              'foreach (var n in Fib().Take(5)) Console.Write($"{n} "); // 0 1 1 2 3',
              '```',
            ),
            { tags: ['csharp'], ratings: LEARNING },
          ),
          basic(
            '`IDisposable` / `using` — детерминированное освобождение',
            md(
              'Освобождает **неуправляемые** ресурсы (файлы, сокеты, соединения) сразу,',
              'не дожидаясь GC. `using` гарантирует `Dispose()` даже при исключении.',
              '',
              '```csharp',
              'using var conn = new SqlConnection(cs); // Dispose в конце scope',
              'await conn.OpenAsync();',
              '',
              '// async-ресурс:',
              'await using var stream = File.OpenRead(path);',
              '```',
            ),
            { tags: ['csharp'], ratings: MATURE },
          ),
          basic(
            'Nullable reference types (NRT)',
            md(
              '`#nullable enable` — компилятор различает `string` и `string?` и требует',
              'проверки перед разыменованием. Это **подсказки времени компиляции**, в',
              'рантайме типы те же.',
              '',
              '```csharp',
              '#nullable enable',
              'string? name = GetName();',
              'int len = name.Length;        // CS8602: возможен null',
              'int ok  = name?.Length ?? 0;  // безопасно',
              '```',
            ),
            { tags: ['csharp'], ratings: STUDIED },
          ),
          basic(
            '`delegate` vs `event`',
            md(
              '`delegate` — функциональный тип (список вызовов). `event` — обёртка над',
              'делегатом с инкапсуляцией: снаружи доступны только `+=` / `-=`, вызвать',
              '(`Invoke`) может только класс-владелец.',
              '',
              '```csharp',
              'public event EventHandler<OrderPlaced>? Placed;',
              'protected void OnPlaced(OrderPlaced e) => Placed?.Invoke(this, e);',
              '```',
            ),
            { tags: ['csharp'], ratings: STUDIED },
          ),
          basic(
            'IL → JIT → нативный код — как .NET исполняет сборку?',
            md(
              'Исходник → **IL** (Intermediate Language) в сборке → **JIT** компилирует',
              'метод в нативный код при первом вызове → CPU. AOT (`PublishAot`) делает',
              'нативную компиляцию заранее.',
              '',
              '```mermaid',
              'flowchart LR',
              '    A["C# source"] --> B["Roslyn"]',
              '    B --> C["IL + metadata (.dll)"]',
              '    C --> D["CLR / JIT"]',
              '    D --> E["native code"]',
              '    C -.PublishAot.-> F["ahead-of-time native"]',
              '```',
            ),
            { tags: ['csharp', 'runtime'], ratings: NEW },
          ),
          basic(
            'GC generations — почему поколения?',
            md(
              'Поколенческий сборщик: большинство объектов умирают молодыми, поэтому',
              'GC чаще собирает Gen 0 (дёшево) и редко — Gen 2.',
              '',
              '- **Gen 0** — свежие объекты, сборка очень частая и быстрая;',
              '- **Gen 1** — пережившие одну сборку (буфер);',
              '- **Gen 2** — долгожители + **LOH** (≥ 85 000 байт), сборка дорогая.',
              '',
              '> Меньше аллокаций в горячем пути → реже Gen 2 → ниже latency-хвост.',
            ),
            { tags: ['csharp', 'runtime', 'perf'], ratings: NEW },
          ),
        ],
      },
      {
        name: 'ASP.NET Core',
        color: 'violet',
        notes: [
          basic(
            'Middleware pipeline — что определяет порядок и что такое short-circuit?',
            md(
              'Упорядоченная цепочка `app.Use(...)`. Каждый middleware решает: вызвать',
              '`next()` (пойти дальше) или **замкнуть** (short-circuit) и вернуть ответ.',
              'Порядок критичен: `UseAuthentication` ДО `UseAuthorization`.',
              '',
              '```mermaid',
              'flowchart LR',
              '    R["Request"] --> EX["Exception handler"]',
              '    EX --> ST["Static files"]',
              '    ST --> RT["Routing"]',
              '    RT --> AUTHN["Authentication"]',
              '    AUTHN --> AUTHZ["Authorization"]',
              '    AUTHZ --> EP["Endpoint"]',
              '    EP --> RESP["Response"]',
              '```',
              '',
              '```csharp',
              'app.UseExceptionHandler();',
              'app.UseStaticFiles();',
              'app.UseRouting();',
              'app.UseAuthentication();',
              'app.UseAuthorization();',
              'app.MapControllers();',
              '```',
            ),
            { tags: ['aspnet'], ratings: MATURE },
          ),
          basic(
            'DI lifetimes — `Singleton` vs `Scoped` vs `Transient`',
            md(
              '| Lifetime | Сколько живёт | Когда брать |',
              '| --- | --- | --- |',
              '| `Singleton` | один на приложение | конфиг, кэш, stateless-сервисы |',
              '| `Scoped` | один на HTTP-request | `DbContext`, unit-of-work |',
              '| `Transient` | новый при каждом resolve | лёгкие, без состояния |',
              '',
              '> **Captive dependency**: внедрить `Scoped` в `Singleton` — баг. Singleton',
              '> захватит первый scope навсегда. Для этого есть `IServiceScopeFactory`.',
              '',
              '```csharp',
              'builder.Services.AddSingleton<IClock, SystemClock>();',
              'builder.Services.AddScoped<IUserRepo, UserRepo>();',
              'builder.Services.AddTransient<IEmailSender, SmtpSender>();',
              '```',
            ),
            { tags: ['aspnet', 'di'], ratings: MATURE },
          ),
          basic(
            'Жизненный цикл HTTP-запроса в ASP.NET Core',
            md(
              '```mermaid',
              'sequenceDiagram',
              '    participant C as Client',
              '    participant K as Kestrel',
              '    participant M as Middleware',
              '    participant A as Action',
              '    participant DB as DbContext',
              '    C->>K: HTTP request',
              '    K->>M: HttpContext',
              '    M->>M: auth, routing, filters',
              '    M->>A: model binding + validation',
              '    A->>DB: query (scoped)',
              '    DB-->>A: rows',
              '    A-->>C: IActionResult → 200/4xx',
              '```',
            ),
            { tags: ['aspnet'], ratings: STUDIED },
          ),
          basic(
            'AuthN vs AuthZ',
            md(
              '- **Authentication (AuthN)** — *кто ты*: cookie, JWT, OAuth/OIDC. Результат — `ClaimsPrincipal`.',
              '- **Authorization (AuthZ)** — *что тебе можно*: роли, policy, claims.',
              '',
              '```csharp',
              'builder.Services.AddAuthorization(o =>',
              '    o.AddPolicy("AdultOnly", p => p.RequireClaim("age", "18+")));',
              '',
              '[Authorize(Policy = "AdultOnly")]',
              'public IActionResult Buy() => Ok();',
              '```',
            ),
            { tags: ['aspnet', 'security'], ratings: MATURE },
          ),
          basic(
            'Minimal API vs Controllers',
            md(
              '```csharp',
              '// Minimal API — минимум церемоний',
              'app.MapGet("/cards/{id}", async (Guid id, ICardRepo repo) =>',
              '    await repo.Find(id) is {} c ? Results.Ok(c) : Results.NotFound());',
              '',
              '// Controller — атрибуты, filters, model binding из коробки',
              '[ApiController, Route("cards")]',
              'public class CardsController(ICardRepo repo) : ControllerBase {',
              '    [HttpGet("{id}")] public Task<Card?> Get(Guid id) => repo.Find(id);',
              '}',
              '```',
              '',
              'Minimal — быстрый старт, микросервисы. Controllers — крупные API с filters/conventions.',
            ),
            { tags: ['aspnet'], ratings: STUDIED },
          ),
          basic(
            '`IOptions<T>` vs `IOptionsSnapshot<T>` vs `IOptionsMonitor<T>`',
            md(
              '| Интерфейс | Когда читает конфиг | Lifetime |',
              '| --- | --- | --- |',
              '| `IOptions<T>` | один раз на старте | singleton |',
              '| `IOptionsSnapshot<T>` | на каждый request | scoped |',
              '| `IOptionsMonitor<T>` | реактивно, `OnChange` | singleton |',
              '',
              '```csharp',
              'builder.Services.Configure<SmtpOptions>(config.GetSection("Smtp"));',
              '```',
            ),
            { tags: ['aspnet', 'config'], ratings: LEARNING },
          ),
          basic(
            'Model binding — источники данных',
            md(
              'Маппинг HTTP-запроса в параметры экшена. Источники по убыванию явности:',
              '',
              '- `[FromRoute]` — сегмент пути `/{id}`',
              '- `[FromQuery]` — строка запроса `?page=2`',
              '- `[FromBody]` — тело (JSON); **только один** на экшен',
              '- `[FromHeader]` / `[FromForm]` / `[FromServices]`',
              '',
              '> Сложные типы по умолчанию биндятся из body, простые — из route/query.',
            ),
            { tags: ['aspnet'], ratings: STUDIED },
          ),
          basic(
            'ProblemDetails (RFC 7807) — стандарт ошибок API',
            md(
              'Единый JSON-формат ошибок: `type` / `title` / `status` / `detail` / `instance`.',
              '',
              '```json',
              '{',
              '  "type": "https://httpstatuses.io/409",',
              '  "title": "Card is suspended",',
              '  "status": 409,',
              '  "detail": "Card 7f3a… is a leech and cannot be reviewed",',
              '  "instance": "/reviews"',
              '}',
              '```',
              '',
              '```csharp',
              'builder.Services.AddProblemDetails();',
              '```',
            ),
            { tags: ['aspnet'], ratings: NEW },
          ),
          basic(
            'CORS — почему куки не ходят cross-origin?',
            md(
              'Браузер блокирует cross-origin запросы без явного разрешения сервера.',
              'Для отправки куки нужны ОБА условия: `AllowCredentials` на сервере и',
              '`credentials: "include"` на клиенте. С credentials нельзя `AllowAnyOrigin`.',
              '',
              '```csharp',
              'app.UseCors(p => p',
              '    .WithOrigins("http://localhost:3001")',
              '    .AllowCredentials()',
              '    .AllowAnyHeader().AllowAnyMethod());',
              '```',
            ),
            { tags: ['aspnet', 'security'], ratings: ROUGH },
          ),
          basic(
            '`BackgroundService` / `IHostedService`',
            md(
              'Долгоживущие фоновые задачи, стартуют/останавливаются вместе с хостом.',
              '`BackgroundService` — удобный базовый класс с `ExecuteAsync`.',
              '',
              '```csharp',
              'public class OutboxPublisher(IServiceProvider sp) : BackgroundService {',
              '    protected override async Task ExecuteAsync(CancellationToken ct) {',
              '        while (!ct.IsCancellationRequested) {',
              '            await PublishPending(ct);',
              '            await Task.Delay(TimeSpan.FromSeconds(5), ct);',
              '        }',
              '    }',
              '}',
              '```',
            ),
            { tags: ['aspnet'], ratings: LEARNING },
          ),
        ],
      },
      {
        name: 'EF Core',
        color: 'violet',
        notes: [
          basic(
            'N+1 query problem — как распознать и убить?',
            md(
              'Итерация по коллекции, где обращение к навигации стреляет отдельным',
              'запросом на КАЖДЫЙ элемент: 1 запрос на список + N на детали.',
              '',
              '```csharp',
              '// ПЛОХО: 1 + N запросов',
              'foreach (var d in db.Decks) Console.WriteLine(d.Cards.Count);',
              '',
              '// ХОРОШО: один JOIN',
              'var decks = db.Decks.Include(d => d.Cards).ToList();',
              '```',
              '',
              '```sql',
              '-- было: повтор на каждую колоду',
              'SELECT * FROM cards WHERE deck_id = @p0;',
              '-- стало: один проход',
              'SELECT d.*, c.* FROM decks d LEFT JOIN cards c ON c.deck_id = d.id;',
              '```',
            ),
            { tags: ['ef', 'perf', 'db'], ratings: MATURE },
          ),
          basic(
            'Eager vs Lazy vs Explicit loading',
            md(
              '- **Eager** — `Include(x => x.Posts)`: грузим заранее одним запросом.',
              '- **Lazy** — proxy-классы, запрос при первом обращении к навигации (риск N+1).',
              '- **Explicit** — `ctx.Entry(e).Collection(x => x.Posts).Load()` вручную.',
              '',
              '```csharp',
              'var blog = db.Blogs',
              '    .Include(b => b.Posts).ThenInclude(p => p.Comments)',
              '    .First();',
              '```',
            ),
            { tags: ['ef'], ratings: ROUGH },
          ),
          basic(
            '`AsNoTracking()` — когда?',
            md(
              'Отключает change tracker: EF не снимает снапшоты сущностей. Для **read-only**',
              'запросов — заметно меньше памяти и быстрее, потому что нечего отслеживать.',
              '',
              '```csharp',
              'var cards = await db.Cards',
              '    .AsNoTracking()',
              '    .Where(c => c.DeckId == id)',
              '    .ToListAsync();',
              '```',
              '',
              '> Если потом будешь звать `SaveChanges` по этим сущностям — не используй.',
            ),
            { tags: ['ef', 'perf'], ratings: STUDIED },
          ),
          basic(
            'Миграции EF Core — команды и поток',
            md(
              '```bash',
              '# создать миграцию по diff модели',
              'dotnet ef migrations add AddLeechFlag',
              '# применить локально',
              'dotnet ef database update',
              '# для CI/прод — SQL-скрипт идемпотентный',
              'dotnet ef migrations script --idempotent -o migrate.sql',
              '```',
              '',
              'Code First: модель C# → `OnModelCreating` (Fluent API) → миграция → SQL.',
            ),
            { tags: ['ef', 'migrations'], ratings: STUDIED },
          ),
          basic(
            'Optimistic concurrency token',
            md(
              'Поле-версия (`[Timestamp]` rowversion или `IsConcurrencyToken`). EF добавляет',
              '`WHERE version = @old` в `UPDATE`; если затронуто 0 строк — кто-то опередил →',
              '`DbUpdateConcurrencyException`.',
              '',
              '```csharp',
              'public class Card {',
              '    public Guid Id { get; set; }',
              '    [Timestamp] public byte[] Version { get; set; } = default!;',
              '}',
              '```',
              '',
              '```sql',
              'UPDATE cards SET stability = @s WHERE id = @id AND version = @old;',
              '-- 0 rows affected → conflict',
              '```',
            ),
            { tags: ['ef', 'concurrency'], ratings: NEW },
          ),
          basic(
            'Global query filters — soft delete / multitenancy',
            md(
              'Условие, которое EF автоматически добавляет в КАЖДЫЙ запрос по сущности.',
              '',
              '```csharp',
              'modelBuilder.Entity<Card>()',
              '    .HasQueryFilter(c => !c.IsDeleted);',
              '',
              '// обойти фильтр там, где надо видеть всё:',
              'db.Cards.IgnoreQueryFilters().ToList();',
              '```',
            ),
            { tags: ['ef'], ratings: LEARNING },
          ),
          basic(
            '`FromSqlInterpolated` vs `FromSqlRaw` — безопасность',
            md(
              '- `FromSqlInterpolated($"… {id}")` — интерполяция превращается в **параметры** (безопасно).',
              '- `FromSqlRaw("… " + id)` — конкатенация строк → **SQL-инъекция**.',
              '',
              '```csharp',
              '// безопасно: id уходит как @p0',
              'db.Cards.FromSqlInterpolated($"SELECT * FROM cards WHERE id = {id}");',
              '```',
            ),
            { tags: ['ef', 'security'], ratings: LEARNING },
          ),
        ],
      },
      {
        name: 'Архитектура и паттерны',
        color: 'neutral',
        notes: [
          basic(
            'Clean Architecture — направление зависимостей',
            md(
              'Концентрические слои; зависимости смотрят **внутрь**, к домену.',
              'Инфраструктура — плагин, подключаемый через интерфейсы домена.',
              '',
              '```mermaid',
              'flowchart TB',
              '    subgraph Outer',
              '      INFRA["Infrastructure (EF, HTTP)"]',
              '      UI["Presentation (API/Web)"]',
              '    end',
              '    APP["Application (use cases)"]',
              '    DOM["Domain (entities, rules)"]',
              '    UI --> APP',
              '    INFRA --> APP',
              '    APP --> DOM',
              '```',
              '',
              '> Домен не знает про EF/HTTP. Инверсия зависимостей делает его тестируемым.',
            ),
            { tags: ['architecture', 'solid'], ratings: LEARNING },
          ),
          basic(
            'CQRS — зачем разделять чтение и запись?',
            md(
              'Command Query Responsibility Segregation: команды (мутации) и запросы',
              '(чтение) идут разными путями/моделями. Чтение можно денормализовать и',
              'масштабировать независимо. Часто оркеструется через MediatR.',
              '',
              '```mermaid',
              'flowchart LR',
              '    C["Client"] -->|Command| CH["Command handler"] --> W[("Write DB")]',
              '    C -->|Query| QH["Query handler"] --> R[("Read model")]',
              '    W -.projection.-> R',
              '```',
            ),
            { tags: ['patterns', 'architecture'], ratings: LEARNING },
          ),
          basic(
            'SOLID — пять принципов одной строкой',
            md(
              '- **S** · Single Responsibility — один класс, одна причина для изменения.',
              '- **O** · Open/Closed — открыт для расширения, закрыт для модификации.',
              '- **L** · Liskov Substitution — подтип работает везде, где ждут базовый.',
              '- **I** · Interface Segregation — много узких интерфейсов > один жирный.',
              '- **D** · Dependency Inversion — оба слоя зависят от абстракции, не друг от друга.',
            ),
            { tags: ['solid'], ratings: MATURE },
          ),
          basic(
            'Liskov Substitution — классический антипример',
            md(
              '`Square extends Rectangle` ломает LSP: код, ожидающий `Rectangle`, считает',
              'ширину и высоту независимыми, а квадрат это нарушает.',
              '',
              '```csharp',
              'void Stretch(Rectangle r) {',
              '    r.Width = 5; r.Height = 4;',
              '    Debug.Assert(r.Area == 20); // упадёт для Square (Area == 16)',
              '}',
              '```',
            ),
            { tags: ['solid'], ratings: LEARNING },
          ),
          basic(
            'Dependency Injection — принцип (не контейнер)',
            md(
              'Зависимости **передаются** (обычно через конструктор), а не создаются внутри.',
              'Ослабляет связность, делает класс тестируемым через подстановку фейков.',
              '',
              '```csharp',
              '// плохо: жёсткая связь, не подменить в тесте',
              'class Service { readonly Repo _r = new Repo(); }',
              '// хорошо: инверсия',
              'class Service(IRepo r) { /* r внедрён снаружи */ }',
              '```',
            ),
            { tags: ['patterns', 'solid'], ratings: MATURE },
          ),
          basic(
            'DDD · Aggregate root',
            md(
              'Кластер сущностей с единой границей согласованности. Снаружи ссылаются',
              'ТОЛЬКО на корень; он защищает инварианты всей группы и единица транзакции.',
              '',
              '> `Order` (root) владеет `OrderLine[]`. Менять строки можно только через',
              '> методы заказа — так инвариант «сумма ≥ 0» не обойти.',
            ),
            { tags: ['ddd', 'architecture'], ratings: NEW },
          ),
          basic(
            'Repository pattern — и почему он часто лишний поверх EF',
            md(
              'Абстракция над хранилищем: `IUserRepo.GetById/Add/Remove`. Плюс — изоляция',
              'домена от ORM. Минус — `DbContext` сам по себе уже Repository + Unit of Work,',
              'так что тонкая обёртка часто только дублирует API без выгоды.',
            ),
            { tags: ['patterns'], ratings: STUDIED },
          ),
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // Frontend
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Frontend',
    color: 'lime',
    children: [
      {
        name: 'React',
        color: 'lime',
        notes: [
          basic(
            'Цикл рендера React — от setState до DOM',
            md(
              '```mermaid',
              'flowchart LR',
              '    S["setState"] --> R["render() — новый VDOM"]',
              '    R --> D["diff / reconciliation"]',
              '    D --> C["commit в реальный DOM"]',
              '    C --> E["useEffect (после paint)"]',
              '```',
              '',
              'Рендер — **чистая** фаза (только вычисление VDOM, без сайд-эффектов).',
              'Мутации DOM — в фазе commit. Эффекты — после.',
            ),
            { tags: ['react'], ratings: STUDIED },
          ),
          basic(
            '`useEffect` — deps и cleanup',
            md(
              'Сайд-эффект после коммита. Массив зависимостей решает, когда перезапускать;',
              '`return` — функция очистки (перед следующим запуском и при размонтировании).',
              '',
              '```tsx',
              'useEffect(() => {',
              '  const id = setInterval(tick, 1000);',
              '  return () => clearInterval(id); // cleanup',
              '}, [tick]);',
              '```',
              '',
              '> Пустой `[]` → один раз на mount. Нет массива → каждый рендер (почти всегда баг).',
            ),
            { tags: ['react', 'hooks'], ratings: MATURE },
          ),
          basic(
            '`useMemo` vs `useCallback`',
            md(
              '| Хук | Мемоизирует | Эквивалент |',
              '| --- | --- | --- |',
              '| `useMemo(fn, d)` | **значение** `fn()` | — |',
              '| `useCallback(fn, d)` | **саму функцию** | `useMemo(() => fn, d)` |',
              '',
              '```tsx',
              'const sorted = useMemo(() => items.sort(cmp), [items]);',
              'const onPick = useCallback((id: string) => select(id), [select]);',
              '```',
              '',
              '> Не оборачивай всё подряд — мемоизация сама стоит памяти и сравнений.',
            ),
            { tags: ['react', 'hooks', 'perf'], ratings: STUDIED },
          ),
          basic(
            'Reconciliation — как React сверяет деревья',
            md(
              'Эвристика O(n) вместо общего O(n³):',
              '',
              '1. **разный тип** узла → unmount старого, mount нового поддерева;',
              '2. **тот же тип** → обновить props, рекурсивно сравнить детей;',
              '3. списки сверяются по **`key`** — стабильный id, НЕ индекс.',
              '',
              '> Индекс как key + переупорядочивание = перепутанное состояние строк.',
            ),
            { tags: ['react'], ratings: ROUGH },
          ),
          basic(
            'Почему key — это id, а не index?',
            md(
              'При вставке в начало списка индексы всех элементов сдвигаются, React решает',
              'что изменились ВСЕ — и переиспользует не те DOM-узлы (теряется фокус, состояние input).',
              '',
              '```tsx',
              '// плохо при реордере/вставке',
              'rows.map((r, i) => <Row key={i} {...r} />)',
              '// хорошо',
              'rows.map((r) => <Row key={r.id} {...r} />)',
              '```',
            ),
            { tags: ['react'], ratings: MATURE },
          ),
          basic(
            'React Server Components — чем отличаются?',
            md(
              'Рендерятся на сервере, **не отправляют свой JS** в браузер, могут читать',
              'server-only ресурсы (БД, секреты) прямо в теле. Без состояния и эффектов;',
              'интерактив выносится в Client Components (`"use client"`).',
              '',
              '| | Server Component | Client Component |',
              '| --- | --- | --- |',
              '| JS в бандле | нет | да |',
              '| useState/useEffect | нет | да |',
              '| доступ к БД/секретам | да | нет |',
            ),
            { tags: ['react', 'nextjs'], ratings: LEARNING },
          ),
          basic(
            '`React.memo` — и почему он часто не срабатывает',
            md(
              'HOC: пропускает ре-рендер, если пропсы **shallow-equal**. Ломается, когда',
              'каждый рендер передаёт НОВУЮ ссылку:',
              '',
              '```tsx',
              '// новый объект/функция каждый рендер → memo бесполезен',
              '<Child style={makeStyle()} onClick={() => f()} />',
              '// стабилизируй ссылки: useMemo для объекта, useCallback для функции',
              '```',
            ),
            { tags: ['react', 'perf'], ratings: STUDIED },
          ),
          basic(
            'React Query (TanStack) — server-state кэш',
            md(
              'Кэш серверного состояния: дедупликация, retry, stale-while-revalidate,',
              'инвалидация после мутаций.',
              '',
              '```tsx',
              'const { data, isPending } = useQuery({',
              '  queryKey: ["cards", deckId],',
              '  queryFn: () => api.cards.list(deckId),',
              '});',
              '',
              'const mut = useMutation({',
              '  mutationFn: api.cards.create,',
              '  onSuccess: () => qc.invalidateQueries({ queryKey: ["cards"] }),',
              '});',
              '```',
            ),
            { tags: ['react', 'data'], ratings: STUDIED },
          ),
          basic(
            'Controlled vs Uncontrolled inputs',
            md(
              '- **Controlled** — значение в state, `onChange` обновляет. React = источник истины.',
              '- **Uncontrolled** — DOM хранит значение, читаем через `ref` + `defaultValue`.',
              '',
              '```tsx',
              '// controlled',
              '<input value={name} onChange={(e) => setName(e.target.value)} />',
              '// uncontrolled',
              '<input ref={ref} defaultValue="anon" />',
              '```',
            ),
            { tags: ['react'], ratings: STUDIED },
          ),
        ],
      },
      {
        name: 'TypeScript',
        color: 'sky',
        notes: [
          basic(
            'Generics — `<T>` и ограничения `extends`',
            md(
              '```ts',
              'function identity<T>(x: T): T { return x; }',
              '',
              '// ограничение: T обязан иметь length',
              'function longest<T extends { length: number }>(a: T, b: T): T {',
              '  return a.length >= b.length ? a : b;',
              '}',
              'longest([1, 2], [1]);   // ok',
              'longest("abcd", "ab");  // ok',
              '```',
            ),
            { tags: ['ts', 'generic'], ratings: MATURE },
          ),
          basic(
            'Utility types — шпаргалка',
            md(
              '| Тип | Делает |',
              '| --- | --- |',
              '| `Partial<T>` | все поля опциональны |',
              '| `Required<T>` | все поля обязательны |',
              '| `Readonly<T>` | все поля только для чтения |',
              '| `Pick<T, K>` | оставить ключи `K` |',
              '| `Omit<T, K>` | убрать ключи `K` |',
              '| `Record<K, V>` | объект `K → V` |',
              '| `ReturnType<F>` | тип возврата функции |',
              '| `NonNullable<T>` | убрать `null` и `undefined` |',
            ),
            { tags: ['ts', 'utility'], ratings: MATURE },
          ),
          basic(
            'Discriminated union — безопасный полиморфизм данных',
            md(
              'Union с общим литеральным полем-дискриминатором; компилятор сужает по нему',
              'и проверяет полноту через `never`.',
              '',
              '```ts',
              'type Result<T> =',
              '  | { kind: "ok"; value: T }',
              '  | { kind: "err"; error: string };',
              '',
              'function unwrap<T>(r: Result<T>): T {',
              '  switch (r.kind) {',
              '    case "ok":  return r.value;',
              '    case "err": throw new Error(r.error);',
              '  }',
              '}',
              '```',
            ),
            { tags: ['ts'], ratings: STUDIED },
          ),
          basic(
            'Type guard — функция `x is T`',
            md(
              'Пользовательский предикат, который сужает тип в ветке `if`:',
              '',
              '```ts',
              'function isString(x: unknown): x is string {',
              '  return typeof x === "string";',
              '}',
              '',
              'function len(x: unknown) {',
              '  if (isString(x)) return x.length; // x: string',
              '  return 0;',
              '}',
              '```',
            ),
            { tags: ['ts'], ratings: LEARNING },
          ),
          basic(
            '`infer` в conditional types',
            md(
              'Захватывает выведенный тип внутри условного типа:',
              '',
              '```ts',
              'type ElementOf<A> = A extends (infer U)[] ? U : never;',
              'type Ret<F> = F extends (...args: any[]) => infer R ? R : never;',
              '',
              'type X = ElementOf<number[]>; // number',
              'type Y = Ret<() => string>;   // string',
              '```',
            ),
            { tags: ['ts'], ratings: ROUGH },
          ),
          basic(
            '`satisfies` vs `as`',
            md(
              '`as` **подменяет** тип (можно соврать компилятору). `satisfies` **проверяет**',
              'соответствие, но СОХРАНЯЕТ узкий выведенный тип значения.',
              '',
              '```ts',
              'const cfg = {',
              '  port: 3000,',
              '  host: "localhost",',
              '} satisfies Record<string, string | number>;',
              '',
              'cfg.port.toFixed(0); // port всё ещё number, не string|number',
              '```',
            ),
            { tags: ['ts'], ratings: NEW },
          ),
          basic(
            '`keyof` и lookup-типы `T[K]`',
            md(
              '```ts',
              'interface User { id: string; age: number; }',
              'type Keys = keyof User;   // "id" | "age"',
              'type Age  = User["age"];  // number',
              '',
              '// типобезопасный геттер свойства',
              'function prop<T, K extends keyof T>(o: T, k: K): T[K] { return o[k]; }',
              '```',
            ),
            { tags: ['ts'], ratings: LEARNING },
          ),
        ],
      },
      {
        name: 'CSS',
        color: 'sky',
        notes: [
          basic(
            'Flexbox — главная и поперечная ось',
            md(
              'main-axis задаётся `flex-direction`; cross-axis ей перпендикулярна.',
              '`justify-content` управляет main, `align-items` — cross.',
              '',
              '```css',
              '.row {',
              '  display: flex;',
              '  flex-direction: row;     /* main = горизонталь */',
              '  justify-content: space-between; /* вдоль main */',
              '  align-items: center;     /* поперёк */',
              '}',
              '```',
            ),
            { tags: ['css'], ratings: STUDIED },
          ),
          basic(
            'CSS specificity — как считается?',
            md(
              'Вес селектора — кортеж `(a, b, c)`: a = inline/ID-веса, b = классы/атрибуты/',
              'псевдоклассы, c = теги/псевдоэлементы. Сравнение слева направо.',
              '',
              '| Селектор | (a, b, c) |',
              '| --- | --- |',
              '| `div` | (0, 0, 1) |',
              '| `.btn` | (0, 1, 0) |',
              '| `#id` | (1, 0, 0) |',
              '| `a.btn:hover` | (0, 2, 1) |',
              '',
              '> `!important` перебивает каскад — крайняя мера, не инструмент.',
            ),
            { tags: ['css'], ratings: STUDIED },
          ),
          basic(
            'z-index gotcha — stacking context',
            md(
              '`z-index` работает только на **positioned** элементах (не `static`).',
              'Новый stacking context (создаётся `position` + z-index, `opacity < 1`,',
              '`transform`, `filter`…) **изолирует** потомков: высокий z-index ВНУТРИ',
              'контекста не вылезет наружу за пределы самого контекста.',
              '',
              '> Модалка «прячется» под шапкой? Скорее всего, родитель создал новый context.',
            ),
            { tags: ['css'], ratings: ROUGH },
          ),
          basic(
            'CSS custom properties (переменные)',
            md(
              'Каскадируются и наследуются, читаются через `var()`, меняются в рантайме.',
              '',
              '```css',
              ':root { --accent: #b6ff3c; --r-md: 12px; }',
              '.btn { background: var(--accent); border-radius: var(--r-md); }',
              '[data-theme="light"] { --accent: #2f7a00; }',
              '```',
              '',
              '```ts',
              'el.style.setProperty("--accent", "#ff5c8a"); // динамически',
              '```',
            ),
            { tags: ['css'], ratings: STUDIED },
          ),
          basic(
            'Grid — единица `fr`',
            md(
              'Fractional unit — доля свободного места после фиксированных треков.',
              '',
              '```css',
              '.layout {',
              '  display: grid;',
              '  grid-template-columns: 240px 1fr 2fr; /* сайдбар + 1:2 контент */',
              '  gap: 16px;',
              '}',
              '```',
            ),
            { tags: ['css'], ratings: STUDIED },
          ),
          basic(
            '`position: sticky`',
            md(
              'Элемент ведёт себя как `relative`, пока скролл не доведёт его до порога',
              '(`top`/`bottom`), затем «прилипает» как `fixed` в пределах родителя.',
              '',
              '```css',
              '.toolbar { position: sticky; top: 0; z-index: 10; }',
              '```',
              '',
              '> Не работает, если у родителя `overflow: hidden/auto` или нет высоты.',
            ),
            { tags: ['css'], ratings: LEARNING },
          ),
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // Computer Science
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Computer Science',
    color: 'sky',
    children: [
      {
        name: 'Алгоритмы',
        color: 'sky',
        notes: [
          basic(
            'Big-O — таблица классов сложности',
            md(
              'Верхняя асимптотическая оценка роста (худший случай), без констант.',
              '',
              '| Класс | Название | Пример |',
              '| --- | --- | --- |',
              '| \\( O(1) \\) | константа | доступ по индексу, hash get |',
              '| \\( O(\\log n) \\) | логарифм | binary search, сбалансированное BST |',
              '| \\( O(n) \\) | линейная | один проход массива |',
              '| \\( O(n \\log n) \\) | линеарифм. | merge/quick/heap sort |',
              '| \\( O(n^2) \\) | квадрат | вложенные циклы, bubble sort |',
              '| \\( O(2^n) \\) | экспонента | наивный перебор подмножеств |',
            ),
            { tags: ['algo'], ratings: MATURE },
          ),
          basic(
            'Binary search — инвариант и реализация',
            md(
              'Только на ОТСОРТИРОВАННОМ массиве, \\( O(\\log n) \\). Инвариант: искомое',
              'всегда внутри полуинтервала `[lo, hi)`.',
              '',
              '```ts',
              'function bsearch(a: number[], x: number): number {',
              '  let lo = 0, hi = a.length;',
              '  while (lo < hi) {',
              '    const mid = (lo + hi) >>> 1; // без переполнения',
              '    if (a[mid] === x) return mid;',
              '    if (a[mid] < x) lo = mid + 1;',
              '    else hi = mid;',
              '  }',
              '  return -1;',
              '}',
              '```',
            ),
            { tags: ['algo'], ratings: MATURE },
          ),
          basic(
            'Master theorem — оценка divide-and-conquer',
            md(
              'Для рекуррентности вида',
              '',
              '\\[ T(n) = a\\,T(n/b) + f(n) \\]',
              '',
              'сравниваем \\( f(n) \\) с \\( n^{\\log_b a} \\):',
              '',
              '- \\( f(n) = O(n^{\\log_b a - \\varepsilon}) \\Rightarrow T(n) = \\Theta(n^{\\log_b a}) \\)',
              '- \\( f(n) = \\Theta(n^{\\log_b a}) \\Rightarrow T(n) = \\Theta(n^{\\log_b a}\\log n) \\)',
              '- \\( f(n) = \\Omega(n^{\\log_b a + \\varepsilon}) \\Rightarrow T(n) = \\Theta(f(n)) \\)',
              '',
              '> Mergesort: \\( a=2, b=2, f(n)=n \\Rightarrow \\Theta(n\\log n) \\).',
            ),
            { tags: ['algo', 'math'], ratings: NEW },
          ),
          basic(
            'BFS vs DFS — обход графа',
            md(
              'BFS — уровень за уровнем (очередь), даёт кратчайший путь в невзвешенном',
              'графе. DFS — вглубь (стек/рекурсия), удобен для топосортировки и компонент.',
              '',
              '```mermaid',
              'flowchart TD',
              '    A((A)) --> B((B))',
              '    A --> C((C))',
              '    B --> D((D))',
              '    C --> D',
              '    C --> E((E))',
              '```',
              '',
              '```ts',
              '// BFS',
              'function bfs(start: Node) {',
              '  const q = [start]; const seen = new Set([start]);',
              '  while (q.length) {',
              '    const n = q.shift()!;',
              '    for (const m of n.adj) if (!seen.has(m)) { seen.add(m); q.push(m); }',
              '  }',
              '}',
              '```',
            ),
            { tags: ['algo', 'graph'], ratings: STUDIED },
          ),
          basic(
            'Dynamic Programming — когда применимо?',
            md(
              'Два признака: **оптимальная подструктура** + **перекрывающиеся подзадачи**.',
              'Решение — мемоизация (top-down) или табуляция (bottom-up).',
              '',
              '```ts',
              '// fib с мемоизацией: O(n) вместо O(2^n)',
              'const memo = new Map<number, number>();',
              'function fib(n: number): number {',
              '  if (n < 2) return n;',
              '  if (memo.has(n)) return memo.get(n)!;',
              '  const r = fib(n - 1) + fib(n - 2);',
              '  memo.set(n, r);',
              '  return r;',
              '}',
              '```',
              '',
              '> Примеры: LIS, knapsack, edit distance, coin change.',
            ),
            { tags: ['algo'], ratings: LEARNING },
          ),
          basic(
            'Quicksort vs Mergesort',
            md(
              '| | Quicksort | Mergesort |',
              '| --- | --- | --- |',
              '| Среднее | \\( O(n\\log n) \\) | \\( O(n\\log n) \\) |',
              '| Худшее | \\( O(n^2) \\) (плохой pivot) | \\( O(n\\log n) \\) |',
              '| Память | \\( O(\\log n) \\), in-place | \\( O(n) \\) доп. |',
              '| Стабильность | нет | да |',
              '',
              '> На практике quicksort быстрее из-за кэш-локальности; mergesort — когда',
              '> нужна стабильность или внешняя сортировка.',
            ),
            { tags: ['algo'], ratings: ROUGH },
          ),
          basic(
            'Two pointers / sliding window',
            md(
              'Два индекса по массиву убирают вложенный цикл: \\( O(n) \\) вместо \\( O(n^2) \\).',
              '',
              '```ts',
              '// самая длинная подстрока без повторов',
              'function longest(s: string): number {',
              '  const seen = new Map<string, number>();',
              '  let lo = 0, best = 0;',
              '  for (let hi = 0; hi < s.length; hi++) {',
              '    const c = s[hi];',
              '    if (seen.has(c) && seen.get(c)! >= lo) lo = seen.get(c)! + 1;',
              '    seen.set(c, hi);',
              '    best = Math.max(best, hi - lo + 1);',
              '  }',
              '  return best;',
              '}',
              '```',
            ),
            { tags: ['algo'], ratings: STUDIED },
          ),
        ],
      },
      {
        name: 'Структуры данных',
        color: 'sky',
        notes: [
          basic(
            'Сложность операций по структурам',
            md(
              '| Структура | Доступ | Поиск | Вставка | Удаление |',
              '| --- | --- | --- | --- | --- |',
              '| Array | \\( O(1) \\) | \\( O(n) \\) | \\( O(n) \\) | \\( O(n) \\) |',
              '| Linked list | \\( O(n) \\) | \\( O(n) \\) | \\( O(1) \\)* | \\( O(1) \\)* |',
              '| Hash map | — | \\( O(1) \\) avg | \\( O(1) \\) avg | \\( O(1) \\) avg |',
              '| BST (balanced) | — | \\( O(\\log n) \\) | \\( O(\\log n) \\) | \\( O(\\log n) \\) |',
              '| Heap | — | \\( O(n) \\) | \\( O(\\log n) \\) | \\( O(\\log n) \\) |',
              '',
              '> \\*при уже известном узле. Array выигрывает по кэшу за счёт смежной памяти.',
            ),
            { tags: ['ds'], ratings: MATURE },
          ),
          basic(
            'HashMap — load factor и ресайз',
            md(
              'Хэш → бакет. Коэффициент загрузки',
              '',
              '\\[ \\alpha = \\frac{n}{m} \\]',
              '',
              'где `n` — элементы, `m` — бакеты. При \\( \\alpha \\) выше порога (≈0.75) таблица',
              'ресайзится (обычно ×2) и всё **рехэшируется**. Хороший хэш держит коллизии',
              'редкими → среднее \\( O(1) \\); вырождение → \\( O(n) \\).',
            ),
            { tags: ['ds'], ratings: STUDIED },
          ),
          basic(
            'BST — инвариант и вырождение',
            md(
              'Для любого узла: `left < node < right`. Сбалансированное (AVL/Red-Black) —',
              '\\( O(\\log n) \\); вставка отсортированных данных без балансировки → «список»,',
              '\\( O(n) \\).',
              '',
              '```mermaid',
              'flowchart TD',
              '    R((8)) --> A((3))',
              '    R --> B((10))',
              '    A --> C((1))',
              '    A --> D((6))',
              '    B --> E((14))',
              '```',
            ),
            { tags: ['ds'], ratings: LEARNING },
          ),
          basic(
            'Heap / Priority Queue',
            md(
              'Полное бинарное дерево с heap-инвариантом (в min-heap родитель ≤ детей),',
              'хранится в массиве: дети узла `i` — это `2i+1` и `2i+2`. Вставка и извлечение',
              'корня — \\( O(\\log n) \\). Для top-k и Dijkstra.',
            ),
            { tags: ['ds'], ratings: LEARNING },
          ),
          basic(
            'Bloom filter — вероятностное множество',
            md(
              'Битовый массив + `k` хэшей. Возможны **false positive**, но НИКОГДА false',
              'negative. Вероятность ложного срабатывания при `n` элементах и `m` битах:',
              '',
              '\\[ p \\approx \\left(1 - e^{-kn/m}\\right)^{k} \\]',
              '',
              '> Применение: «точно нет в кэше/БД?» до дорогого похода на диск.',
            ),
            { tags: ['ds'], ratings: NEW },
          ),
          basic(
            'Stack vs Queue',
            md(
              '- **Stack (LIFO)** — push/pop с одного конца, \\( O(1) \\). Undo, call stack, DFS.',
              '- **Queue (FIFO)** — enqueue в хвост, dequeue из головы, \\( O(1) \\). BFS, планировщик.',
            ),
            { tags: ['ds'], ratings: MATURE },
          ),
        ],
      },
      {
        name: 'Базы данных',
        color: 'sky',
        notes: [
          basic(
            'B-tree индекс — почему он основной в РСУБД?',
            md(
              'Сбалансированное дерево высокого ветвления: один узел = одна страница диска,',
              'высота ≈ \\( \\log_b n \\) → мало чтений. Хорош и для точечного поиска, и для',
              '**range scan** (`BETWEEN`, `ORDER BY`), т.к. листья связаны по порядку.',
              '',
              '```mermaid',
              'flowchart TD',
              '    Root["[ 30 | 60 ]"] --> A["[10|20]"]',
              '    Root --> B["[40|50]"]',
              '    Root --> C["[70|80]"]',
              '```',
            ),
            { tags: ['db'], ratings: STUDIED },
          ),
          basic(
            'Уровни изоляции и аномалии',
            md(
              'Чем выше уровень — тем меньше аномалий, но больше блокировок.',
              '',
              '| Уровень | Dirty read | Non-repeatable | Phantom |',
              '| --- | --- | --- | --- |',
              '| Read Uncommitted | да | да | да |',
              '| Read Committed | нет | да | да |',
              '| Repeatable Read | нет | нет | да* |',
              '| Serializable | нет | нет | нет |',
              '',
              '> \\*в Postgres MVCC RR уже не даёт phantom. Дефолт PG — Read Committed.',
            ),
            { tags: ['db'], ratings: ROUGH },
          ),
          basic(
            'JOIN-ы — типы',
            md(
              '```sql',
              'SELECT d.name, c.front',
              'FROM decks d',
              'INNER JOIN cards c ON c.deck_id = d.id;   -- пересечение',
              '',
              'SELECT d.name, c.front',
              'FROM decks d',
              'LEFT JOIN cards c ON c.deck_id = d.id;    -- все колоды + карты, где есть',
              '```',
              '',
              '- `INNER` — только совпавшие строки;',
              '- `LEFT` — все слева + совпадения справа (иначе NULL);',
              '- `FULL` — всё с обеих сторон; `CROSS` — декартово произведение.',
            ),
            { tags: ['db', 'sql'], ratings: MATURE },
          ),
          basic(
            'Window functions — агрегат без сворачивания строк',
            md(
              '```sql',
              'SELECT',
              '  deck_id,',
              '  front,',
              '  ROW_NUMBER() OVER (PARTITION BY deck_id ORDER BY created_at DESC) AS rn,',
              '  COUNT(*)     OVER (PARTITION BY deck_id) AS deck_total',
              'FROM cards;',
              '```',
              '',
              'Строки НЕ схлопываются (в отличие от `GROUP BY`). Для running totals,',
              'top-N-per-group, ранжирования.',
            ),
            { tags: ['db', 'sql'], ratings: LEARNING },
          ),
          basic(
            '`EXPLAIN ANALYZE` — читаем план запроса',
            md(
              'Показывает, КАК СУБД выполнит/выполнила запрос: способ доступа, стоимость,',
              'оценка vs факт строк.',
              '',
              '```sql',
              'EXPLAIN ANALYZE',
              'SELECT * FROM cards WHERE user_id = $1 AND due < now();',
              '```',
              '',
              '> `Seq Scan` по большой таблице в горячем запросе → не хватает индекса.',
              '> Большой разрыв estimate/actual → устаревшая статистика (`ANALYZE`).',
            ),
            { tags: ['db', 'perf'], ratings: STUDIED },
          ),
          basic(
            'ACID',
            md(
              '| Буква | Гарантия |',
              '| --- | --- |',
              '| **A**tomicity | всё-или-ничего, откат при сбое |',
              '| **C**onsistency | переход между валидными состояниями (инварианты, FK) |',
              '| **I**solation | конкурентные транзакции как будто последовательны |',
              '| **D**urability | зафиксированное переживает падение (WAL) |',
            ),
            { tags: ['db'], ratings: MATURE },
          ),
          basic(
            'Deadlock — как возникает и как лечить',
            md(
              'Две транзакции держат ресурсы и ждут друг друга по кругу. СУБД детектит',
              'цикл и убивает жертву.',
              '',
              '```mermaid',
              'sequenceDiagram',
              '    participant T1',
              '    participant T2',
              '    T1->>A: lock row A',
              '    T2->>B: lock row B',
              '    T1->>B: ждёт B 🔒',
              '    T2->>A: ждёт A 🔒 — deadlock',
              '```',
              '',
              '> Лечение: единый порядок захвата ресурсов, короткие транзакции, retry.',
            ),
            { tags: ['db'], ratings: LEARNING },
          ),
        ],
      },
      {
        name: 'System Design',
        color: 'neutral',
        notes: [
          basic(
            'CAP-теорема',
            md(
              'В распределённой системе при сетевом разделении (**P**) приходится выбирать',
              'между **C** (consistency) и **A** (availability).',
              '',
              '```mermaid',
              'flowchart TD',
              '    P["Network partition случился"] --> Q{выбор}',
              '    Q -->|сохранить консистентность| CP["CP: отказать в ответе"]',
              '    Q -->|сохранить доступность| AP["AP: ответить, возможно устаревшим"]',
              '```',
              '',
              '> P неизбежен в реальной сети, так что выбор всегда между C и A.',
            ),
            { tags: ['sysdesign'], ratings: STUDIED },
          ),
          basic(
            'Cache-aside (lazy loading)',
            md(
              'Приложение само управляет кэшем: промах → читаем БД → кладём в кэш.',
              '',
              '```mermaid',
              'sequenceDiagram',
              '    participant App',
              '    participant Cache',
              '    participant DB',
              '    App->>Cache: get(key)',
              '    Cache-->>App: miss',
              '    App->>DB: SELECT …',
              '    DB-->>App: row',
              '    App->>Cache: set(key, row, ttl)',
              '```',
              '',
              '> Инвалидация — самая сложная часть. TTL + явный bust при записи.',
            ),
            { tags: ['sysdesign'], ratings: STUDIED },
          ),
          basic(
            'Circuit breaker — защита от каскадных отказов',
            md(
              'Обёртка над ненадёжным downstream. После N ошибок «размыкается» и быстро',
              'возвращает ошибку вместо зависания; периодически пробует восстановиться.',
              '',
              '```mermaid',
              'stateDiagram-v2',
              '    [*] --> Closed',
              '    Closed --> Open: порог ошибок',
              '    Open --> HalfOpen: таймаут',
              '    HalfOpen --> Closed: probe ok',
              '    HalfOpen --> Open: probe fail',
              '```',
            ),
            { tags: ['sysdesign'], ratings: LEARNING },
          ),
          basic(
            'Rate limiting — token bucket',
            md(
              'Ведро ёмкости `b` пополняется со скоростью `r` токенов/сек; запрос тратит',
              'токен. Допускает короткие всплески до `b`, держит средний темп `r`.',
              '',
              '\\[ \\text{tokens}(t) = \\min\\left(b,\\ \\text{tokens} + r \\cdot \\Delta t\\right) \\]',
              '',
              '> Альтернативы: leaky bucket (ровный поток), sliding window (точный счёт).',
            ),
            { tags: ['sysdesign'], ratings: STUDIED },
          ),
          basic(
            'Idempotency key — безопасный retry',
            md(
              'Клиент шлёт UUID в заголовке; сервер сохраняет результат под этим ключом.',
              'Повтор того же ключа → возвращается СОХРАНЁННЫЙ ответ, без повторного эффекта.',
              '',
              '```http',
              'POST /payments',
              'Idempotency-Key: 5f1c-9a2b-… ',
              '```',
              '',
              '> Спасает от двойного списания при ретрае по таймауту.',
            ),
            { tags: ['sysdesign'], ratings: NEW },
          ),
          basic(
            'REST vs gRPC vs GraphQL',
            md(
              '| | REST | gRPC | GraphQL |',
              '| --- | --- | --- | --- |',
              '| Формат | JSON/текст | бинарный protobuf | JSON |',
              '| Транспорт | HTTP/1.1+ | HTTP/2 | HTTP |',
              '| Контракт | OpenAPI (опц.) | `.proto` (строгий) | SDL-схема |',
              '| Сила | универсальность, дебаг | скорость, стриминг | клиент задаёт форму |',
              '| Слабость | over/under-fetch | не человекочитаем | сложный кэш/лимиты |',
            ),
            { tags: ['sysdesign'], ratings: LEARNING },
          ),
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // English
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'English',
    color: 'amber',
    children: [
      {
        name: 'IT vocabulary',
        color: 'amber',
        notes: [
          basic(
            'throughput vs latency',
            md(
              'Две РАЗНЫЕ метрики производительности — часто путают.',
              '',
              '- **throughput** /ˈθruːpʊt/ — пропускная способность, *операций в секунду*.',
              '- **latency** /ˈleɪtənsi/ — задержка, *время одного запроса*.',
              '',
              '> "We boosted **throughput** to 5k req/s, but tail **latency** is still 800 ms."',
            ),
            { tags: ['it', 'vocab'], ratings: STUDIED },
          ),
          basic(
            'race condition',
            md(
              '/reɪs kənˈdɪʃn/ — **состояние гонки**: результат зависит от порядка',
              'недетерминированных операций.',
              '',
              '> "We hit a **race condition** between the cache write and the DB commit."',
            ),
            { tags: ['it', 'vocab'], ratings: ROUGH },
          ),
          basic(
            'technical debt',
            md(
              '**технический долг** — компромиссы в коде, за которые позже «платишь» временем.',
              '',
              '> "Shipping this hack now adds **tech debt** we\'ll pay down next sprint."',
            ),
            { tags: ['it', 'vocab', 'idiom'], ratings: STUDIED },
          ),
          basic(
            'rollback',
            md(
              '**откат** к предыдущему рабочему состоянию.',
              '',
              '> "The deploy broke checkout, so we **rolled back** to the last release."',
            ),
            { tags: ['it', 'vocab'], ratings: MATURE },
          ),
          basic(
            'regression',
            md(
              '**регрессия** — сломалось то, что раньше работало.',
              '',
              '> "This change introduced a **regression** in the payment flow."',
            ),
            { tags: ['it', 'vocab'], ratings: LEARNING },
          ),
          basic(
            'scalable / to scale',
            md(
              '**масштабируемый** — выдерживает рост нагрузки.',
              '',
              '> "This design won\'t **scale** beyond ~10k concurrent users."',
            ),
            { tags: ['it', 'vocab'], ratings: STUDIED },
          ),
          basic(
            'edge case',
            md(
              '**крайний/граничный случай** — редкий ввод на границе допустимого.',
              '',
              '> "Did you cover the empty-array **edge case** in the tests?"',
            ),
            { tags: ['it', 'vocab'], ratings: STUDIED },
          ),
          basic(
            'merge conflict',
            md(
              '**конфликт слияния** — Git не может авто-смержить пересекающиеся правки.',
              '',
              '> "I\'ve got a nasty **merge conflict** in `store.ts` after the rebase."',
            ),
            { tags: ['it', 'vocab', 'git'], ratings: STUDIED },
          ),
        ],
      },
      {
        name: 'Meeting phrases',
        color: 'amber',
        notes: [
          basic(
            "Let me follow up on that",
            md(
              'Вежливо: «уточню и вернусь с ответом» — когда не знаешь ответ сразу,',
              'но не хочешь говорить "I don\'t know".',
              '',
              '> "Good question — let me **follow up on that** after the call."',
            ),
            { tags: ['meeting'], ratings: STUDIED },
          ),
          basic(
            "I'd push back on that",
            md(
              'Мягкое «не соглашусь / возражу» без конфликта. Профессиональный способ',
              'оспорить идею, сохранив тон.',
              '',
              '> "I\'d **push back on that** — caching here adds more risk than it saves."',
            ),
            { tags: ['meeting', 'idiom'], ratings: LEARNING },
          ),
          basic(
            "Let's circle back",
            md(
              '«Вернёмся к этому позже» — отложить тему, не закрывая её.',
              '',
              '> "We\'re short on time — let\'s **circle back** to deployment tomorrow."',
            ),
            { tags: ['meeting', 'idiom'], ratings: STUDIED },
          ),
          basic(
            "Let's take this offline",
            md(
              '«Обсудим это отдельно» — когда тема узкая и не для всего митинга.',
              '',
              '> "This is a rabbit hole — let\'s **take it offline**, just the two of us."',
            ),
            { tags: ['meeting', 'idiom'], ratings: LEARNING },
          ),
          basic(
            "Could you elaborate?",
            md(
              '«Можете раскрыть подробнее?» — вежливая просьба пояснить мысль.',
              '',
              '> "Interesting — could you **elaborate** on the trade-off you mentioned?"',
            ),
            { tags: ['meeting'], ratings: STUDIED },
          ),
          basic(
            "That's out of scope",
            md(
              '«Это вне рамок задачи» — вежливый отказ расширять объём работ.',
              '',
              '> "Dark mode is nice, but it\'s **out of scope** for this release."',
            ),
            { tags: ['meeting'], ratings: LEARNING },
          ),
        ],
      },
      {
        name: 'Everyday business',
        color: 'amber',
        notes: [
          basic(
            "I'm swamped",
            md(
              '«Я завален работой» — informal, объясняет, почему нет времени.',
              '',
              '> "Sorry, I\'m **swamped** today — can we reschedule to Thursday?"',
            ),
            { tags: ['idiom'], ratings: STUDIED },
          ),
          basic(
            "On the same page",
            md(
              '«Понимаем друг друга одинаково».',
              '',
              '> "Before we start, let\'s make sure we\'re **on the same page** about the goal."',
            ),
            { tags: ['idiom'], ratings: MATURE },
          ),
          basic(
            "Low-hanging fruit",
            md(
              '«Лёгкие быстрые победы» — простые задачи с хорошим эффектом.',
              '',
              '> "Let\'s knock out the **low-hanging fruit** before the big refactor."',
            ),
            { tags: ['idiom'], ratings: STUDIED },
          ),
          basic(
            "Move the needle",
            md(
              '«Дать заметный эффект», реально что-то изменить.',
              '',
              '> "Micro-optimizations won\'t **move the needle** — fix the N+1 first."',
            ),
            { tags: ['idiom'], ratings: NEW },
          ),
          basic(
            "Bite the bullet",
            md(
              '«Стиснуть зубы» и сделать неприятное, но необходимое.',
              '',
              '> "We\'ll just have to **bite the bullet** and rewrite the legacy parser."',
            ),
            { tags: ['idiom'], ratings: NEW },
          ),
          basic(
            "Ballpark estimate",
            md(
              '«Грубая прикидка», порядок величины без точности.',
              '',
              '> "Can you give me a **ballpark** — days or weeks?"',
            ),
            { tags: ['idiom'], ratings: LEARNING },
          ),
        ],
      },
      // Exercises the Cloze + Type-in builtins (not just Basic) so the seed covers
      // all three note-types end-to-end, with rich content inside them too.
      {
        name: 'Practice',
        color: 'amber',
        notes: [
          cloze(
            md(
              'HTTP-методы и идемпотентность:',
              '',
              '- `GET` — {{c1::safe}} и идемпотентный (только чтение);',
              '- `PUT` — идемпотентный, {{c2::полностью заменяет}} ресурс;',
              '- `POST` — НЕ идемпотентный (создаёт новый ресурс каждый раз).',
            ),
            'Идемпотентный = повтор того же запроса не меняет результат.',
            { tags: ['http', 'cloze'], ratings: STUDIED },
          ),
          cloze(
            'В Big-O бинарный поиск — {{c1::O(log n)}}, наивный вложенный цикл — {{c2::O(n²)}}, а доступ по индексу массива — {{c3::O(1)}}.',
            'Класс сложности — про РОСТ времени с увеличением входа, без констант.',
            { tags: ['algo', 'cloze'], ratings: LEARNING },
          ),
          cloze(
            md(
              'DI-lifetimes в ASP.NET Core:',
              '',
              '- `AddSingleton` — один экземпляр на {{c1::приложение}};',
              '- `AddScoped` — один на {{c2::request}};',
              '- `AddTransient` — новый при каждом {{c3::resolve}}.',
            ),
            'Внедрять Scoped в Singleton нельзя — captive dependency.',
            { tags: ['aspnet', 'di', 'cloze'], ratings: ROUGH },
          ),
          typein(
            'Type the SQL keyword that removes duplicate rows from a result set.',
            'DISTINCT',
            { tags: ['sql', 'typein'], ratings: EASY },
          ),
          typein(
            md(
              'Какой HTTP-метод **полностью заменяет** ресурс (идемпотентно)?',
              '',
              '> Подсказка: не `POST` и не `PATCH`.',
            ),
            'PUT',
            { tags: ['http', 'typein'], ratings: NEW },
          ),
          typein(
            'Введи C#-ключевое слово для асинхронного ожидания Task внутри async-метода.',
            'await',
            { tags: ['csharp', 'typein'], ratings: STUDIED },
          ),
        ],
      },
    ],
  },
];
